name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.0.x'

      - name: Publish
        run: dotnet publish FitCoach3.csproj -c Release -o release --nologo

      - name: Change base tag
        run: sed -i 's/<base href="\/" \/>/<base href="\/FitCoach\/" \/>/g' release/wwwroot/index.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: release/wwwroot
          branch: gh-pages